from typing import Dict, Optional

from langchain.prompts import PromptTemplate

from app.rag.vectorstore import RAGService
from app.services.llama_client import LlamaAPIClient


def is_classified_as_human(analysis: Dict) -> bool:
    human_prob = float(analysis.get("human_probability", 0))
    ai_prob = float(analysis.get("ai_probability", 0))
    return human_prob > ai_prob


async def run_llama_analysis(
    text: str,
    llama_client: Optional[LlamaAPIClient],
    rag_service: RAGService,
) -> Dict:
    context = rag_service.retrieve_relevant_context(text)

    if llama_client is None:
        return {
            "ai_probability": 0.5,
            "human_probability": 0.5,
            "context": context,
            "reasoning": "No API key configured - using fallback response",
            "status": "fallback",
        }

    try:
        analysis_result = await llama_client.analyze_text_with_llama(text, context)
        analysis_result["context"] = context
        analysis_result["status"] = "success"
        return analysis_result
    except Exception as exc:
        print(f"Llama API call failed: {exc}")
        return {
            "ai_probability": 0.5,
            "human_probability": 0.5,
            "context": context,
            "reasoning": f"API call failed: {str(exc)}",
            "status": "error_fallback",
        }


def analyze_with_langchain(text: str, context: str) -> Dict:
    PromptTemplate(
        input_variables=["text", "context"],
        template="""You are an expert AI text detector. Analyze the following text to determine if it was written by a human or generated by AI.

Context about AI vs Human text patterns:
{context}

Text to analyze:
{text}

Please provide your analysis in the following JSON format:
{{
    "ai_probability": <float between 0.0 and 1.0>,
    "human_probability": <float between 0.0 and 1.0>,
    "reasoning": "<detailed explanation of your analysis>",
    "key_indicators": ["<indicator1>", "<indicator2>", "<indicator3>"],
    "confidence": <float between 0.0 and 1.0>
}}

Focus on:
- Writing style consistency
- Vocabulary diversity
- Grammar patterns
- Emotional expression
- Context awareness
- Natural flow and transitions

Analysis:""",
    )

    return {
        "ai_probability": 0.6,
        "human_probability": 0.4,
        "reasoning": f"Analysis using LangChain with context: {context[:100]}...",
        "key_indicators": ["Structured analysis", "Context-aware", "LangChain-powered"],
        "confidence": 0.8,
        "method": "langchain",
    }


def run_langchain_analysis(text: str, rag_service: RAGService) -> Dict:
    context = rag_service.retrieve_relevant_context(text)
    analysis_result = analyze_with_langchain(text, context)
    analysis_result["context"] = context
    analysis_result["status"] = "success"
    analysis_result["method"] = "langchain_rag"
    return analysis_result
