import React, { useState } from 'react';
import './CreateAnalysis.css';
import { apiService } from '../services/api';

function CreateAnalysis({ onCreateAnalysis, onClose }) {
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsAnalyzing(true);
    setError('');

    try {
      // Call the API to analyze the text using apiService
      const analysis = await apiService.analyzeText(content);
      
      // Calculate percentages
      const aiPercent = Math.round(analysis.ai_probability * 100);
      const humanPercent = Math.round(analysis.human_probability * 100);

      // Create analysis with real AI analysis
      onCreateAnalysis({ 
        title, 
        content,
        aiPercent,
        humanPercent,
        analysis: {
          reasoning: analysis.reasoning,
          source: analysis.source,
          extractionMethod: analysis.extraction_method || 'llama_api'
        }
      });

      setTitle('');
      setContent('');
      onClose(); // Go back to main page after successful creation
    } catch (error) {
      console.error('Analysis failed:', error);
      setError('Failed to analyze text. Please try again.');
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleCancel = () => {
    if (!isAnalyzing) {
      setTitle('');
      setContent('');
      setError('');
      onClose();
    }
  };

  return (
    <div className="create-analysis-page">
      <div className="page-header">
        <h1>Make New Analysis</h1>
      </div>
      
      <div className="create-analysis-container">
        <form className="create-analysis-form" onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="title">Analysis Title</label>
            <input
              id="title"
              type="text"
              placeholder="Enter a descriptive title for your analysis"
              value={title}
              onChange={e => setTitle(e.target.value)}
              required
              disabled={isAnalyzing}
            />
          </div>
          
          <div className="form-group">
            <label htmlFor="content">Text Content</label>
            <textarea
              id="content"
              placeholder="Write your text content here. The AI will analyze the writing style, vocabulary, and patterns to determine if it was written by a human or generated by AI."
              value={content}
              onChange={e => setContent(e.target.value)}
              required
              disabled={isAnalyzing}
              rows={12}
            />
            <div className="form-hint">
              💡 Tip: The more content you provide, the more accurate the AI analysis will be.
            </div>
          </div>
          
          {error && <div className="error-message">{error}</div>}
          
          <div className="form-actions">
            <button 
              type="button" 
              className="cancel-button" 
              onClick={handleCancel}
              disabled={isAnalyzing}
            >
              Cancel
            </button>
            <button type="submit" className="submit-button" disabled={isAnalyzing}>
              {isAnalyzing ? 'Analyzing with AI...' : 'Analyze Text'}
            </button>
          </div>
        </form>
        
        {isAnalyzing && (
          <div className="analysis-status">
            <div className="loading-spinner"></div>
            <p>AI is analyzing your text...</p>
            <p className="status-detail">This may take a few seconds</p>
          </div>
        )}
      </div>
    </div>
  );
}

export default CreateAnalysis;
